cudaでの仮想環境作成
kyoto-kaira/no-lose-janken-ai pull request #1
Opened 2024-11-19 17:11 UTC by syarasyoujyu

2024-11-19 21:36 UTC, syarasyoujyu commented
@matsuda-tkm 
出来ました！

2024-11-19 21:37 UTC, syarasyoujyu commented
仮想環境作成＋リファクタリングです

2024-11-19 23:43 UTC, matsuda-tkm commented
ありがとうございます！
時間ないのでアプリまで作りきってください

2024-11-20 03:07 UTC, syarasyoujyu commented
@matsuda-km
アプリ完成しました！

2024-11-20 03:09 UTC, matsuda-tkm commented
ありがとうございます！
ただ動かないです。
コミット [e3d88d3](https://github.com/kyoto-kaira/no-lose-janken-ai/pull/1/commits/e3d88d32871b9a7c3e570ee7896a227c146b6a9c)までは動いていました

 ```
Traceback (most recent call last):
  File "/Users/takumi/github/nf2024/no-lose-janken-ai/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "/Users/takumi/github/nf2024/no-lose-janken-ai/.venv/lib/python3.12/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
  File "/Users/takumi/github/nf2024/no-lose-janken-ai/app.py", line 114, in <module>
    asyncio.run(main())
  File "/Users/takumi/.local/share/uv/python/cpython-3.12.4-macos-aarch64-none/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/takumi/.local/share/uv/python/cpython-3.12.4-macos-aarch64-none/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/takumi/.local/share/uv/python/cpython-3.12.4-macos-aarch64-none/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/takumi/github/nf2024/no-lose-janken-ai/app.py", line 103, in main
    await asyncio.gather(janken, time)
  File "/Users/takumi/github/nf2024/no-lose-janken-ai/app.py", line 61, in janken_game
    hand_tracker.draw_landmarks(image, hand_landmarks)
                                       ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'hand_landmarks' where it is not associated with a value
```

2024-11-20 03:17 UTC, matsuda-tkm commented
- じゃん、けん、ぽんのタイミングを見ようと思うと、わざわざスクロールしなければならない
    - →カメラと文字が一度に見れるようにしたい
- どうあがいてもチョキとしか予測されないです
- グーチョキパーの確率値を表示して欲しい

2024-11-20 03:26 UTC, matsuda-tkm requested changes

2024-11-20 03:26 UTC, matsuda-tkm commented on requirements.txt
- デプロイ時にはここからuv pip installされるのでtorchも追加してください（torchvision, torchaudioは使ってないので不要）
- CPU推論の方が早いのでcudaのバージョンとか気にしなくていいです（GPUはメモリに乗せる時のオーバーヘッドが推論時間短縮幅に対して大きいのでむしろ遅くなる）

2024-11-20 03:43 UTC, matsuda-tkm commented on requirements.txt
↑ちょっとややこしいことやらないと行けなさそうなので無視していいです

2024-11-20 07:42 UTC, syarasyoujyu commented
@matsuda-tkm 
ジャンケンの確率についてモデルの出力値を確認しましたところ、
予測された手: パー

tensor([[[-36.1846, 4.8068, 11.2413]]], device='cuda:0')

予測された手: チョキ

tensor([[[-31.9099, 16.8938, -10.6984]]], device='cuda:0')

予測された手: パー

tensor([[[-31.2439, -0.0931, 1.7190]]], device='cuda:0')
。。。
といったようになっており、負の数が現れている上
最大値のものを予測値としている状態ですので確率を正確に求めるのは千葉さんに聞かないと分からなさそうです。

2024-11-20 07:44 UTC, matsuda-tkm commented
> 負の数が現れている上

→softmaxを取る前だからだと思います

2024-11-20 07:48 UTC, syarasyoujyu commented
了解です！
ありがとうございます

2024-11-20 08:09 UTC, syarasyoujyu commented
> * じゃん、けん、ぽんのタイミングを見ようと思うと、わざわざスクロールしなければならない
>   
>   * →カメラと文字が一度に見れるようにしたい
> * どうあがいてもチョキとしか予測されないです
> * グーチョキパーの確率値を表示して欲しい
もう一度予測Appを動かしてくれませんでしょうか？
あの後試しましたところ、自分のデバイスではグーやパーなども対応できてました。

2024-11-20 08:19 UTC, matsuda-tkm commented
対応ありがとうございます！
ゲーム開始から「最初はぐー・じゃんけん・ポン」が出るまでの時間が短すぎて焦るので、ボタンを押してからもう少し時間空けてもらえると助かります。

2024-11-20 08:57 UTC, syarasyoujyu reviewed
これでどうでしょうか？

2024-11-20 10:17 UTC, matsuda-tkm commented
僕の環境だと上手く動いていないです...

- 「最初はグー・じゃんけん・ポン」が表示されて「ゲーム終了」ボタンが出現して終わる（予測結果が表示されない）
- 右上がずっと「RUNNING...」になっている
- 動画がかくつく

何か心当たりありますか？

2024-11-20 10:23 UTC, matsuda-tkm commented
> 「最初はグー・じゃんけん・ポン」が表示されて「ゲーム終了」ボタンが出現して終わる（予測結果が表示されない）

→あ、なんか数分待ったら数字が出てきました。でもさすがに時間かかりすぎですね（モデルの推論は一瞬で終わるはずです）

2024-11-20 11:41 UTC, syarasyoujyu commented
数分経って手が表示される原因は下のように
[https://drive.google.com/file/d/1OUJRM2C0yb5_eosO0fzeMrBuHWW9Vsyf](url)
そもそも手を表示させ続けていないことに原因だと思います！
そのため
[https://drive.google.com/file/d/1utozVs8rMmx1AwXyQDvjswAkBV10Wbq2](url)
のように最初から手を表示させ続ければ問題ないと思います

2024-11-20 11:47 UTC, syarasyoujyu commented
「手が表示（認識）される＝動画のように画面の手に赤い点が出る」です

2024-11-20 12:36 UTC, matsuda-tkm commented
なるほど、僕の環境（Apple M2）だとWarningでてたのでそれが悪さしてるかもしれないです

一旦デプロイだけするので以下のように変更してpushもらえますか？

### requirements.txt

```txt
matplotlib
opencv-python-headless
streamlit==1.40.1
torch
```

### app.py

```python
import subprocess
subprocess.run(["uv", "pip", "install", "mediapipe", "--no-deps"])

import asyncio

import cv2
import streamlit as st
import torch
from backend.const import JANKEN_LABELS, MODEL_PATH
from backend.hand_tracker import HandTracker
from backend.model import LSTMNet
from streamlit.delta_generator import DeltaGenerator
# ...
```

2024-11-20 13:00 UTC, matsuda-tkm commented
あ、subprocess.runの位置重要なので一番上に置いてください

2024-11-20 13:04 UTC, syarasyoujyu commented
変え終わりました
ただ、今度は自分のところでエラーが起きました。
おそらくPC環境のせいなので、松田さんのAppleで動くなら大丈夫だと思います

> File "C:\Users\yoko1\workspace\no-lose-janken-ai\venv1\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 88, in exec_func_with_error_handling
    result = func()
             ^^^^^^
File "C:\Users\yoko1\workspace\no-lose-janken-ai\venv1\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 579, in code_to_exec
    exec(code, module.__dict__)
File "C:\Users\yoko1\workspace\no-lose-janken-ai\app.py", line 4, in <module>
    subprocess.run(["uv", "pip", "install", "mediapipe", "--no-deps"])
File "C:\Users\yoko1\anaconda3\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\yoko1\anaconda3\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
File "C:\Users\yoko1\anaconda3\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

2024-11-20 13:07 UTC, matsuda-tkm commented on app.py
> +subprocess.run(["uv", "pip", "install", "mediapipe", "--no-deps"])
```suggestion
subprocess.run(["uv", "pip", "install", "mediapipe", "--no-deps", "--system"])
```

2024-11-20 13:14 UTC, matsuda-tkm requested changes

2024-11-20 13:14 UTC, matsuda-tkm commented on app.py
> +subprocess.run(["uv", "pip", "install", "mediapipe", "--no-deps", "--system"])
上手くいかなかったので次の手順踏んでください

1. ちょっとさっき僕がcommitしたので`git pull`してください
2. subprocessのところは以下のように消してください

```suggestion
```

3. requirements.txtを以下のようにしてください

```
mediapipe
streamlit==1.40.1
torch
```

4. packages.txtを追加して以下を記述してください

```
libgl1-mesa-glx
libglib2.0-0
```

2024-11-20 13:25 UTC, syarasyoujyu reviewed
完了しました

2024-11-20 13:28 UTC, matsuda-tkm commented
一応デプロイはできましたがカメラが写りません...。
https://no-lose-janken.streamlit.app/

```
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR

W0000 00:00:1732109235.603390     943 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

W0000 00:00:1732109235.656047     955 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

2024-11-20 13:27:15.673 Examining the path of torch.classes raised: Tried to instantiate class '__path__._path', but it does not exist! Ensure that it is registered via torch::class_

W0000 00:00:1732109238.805556     972 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

W0000 00:00:1732109238.847968     972 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

[ WARN:0@10.121] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video0): can't open camera by index

[ERROR:0@10.122] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range

W0000 00:00:1732109238.915595     988 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

W0000 00:00:1732109238.955278     997 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

W0000 00:00:1732109246.599780    1003 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

W0000 00:00:1732109246.652966    1005 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

W0000 00:00:1732109252.026661    1027 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

W0000 00:00:1732109252.082793    1027 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

[ WARN:1@23.346] global cap_v4l.cpp:999 open VIDEOIO(V4L2:/dev/video0): can't open camera by index

[ERROR:1@23.346] global obsensor_uvc_stream_channel.cpp:158 getStreamChannelGroup Camera index out of range

W0000 00:00:1732109252.147391    1043 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

W0000 00:00:1732109252.187716    1043 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

W0000 00:00:1732109259.803160    1066 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.

W0000 00:00:1732109259.848141    1066 inference_feedback_manager.cc:114] Feedback manager requires a model with a single signature inference. Disabling support for feedback tensors.
```

2024-11-20 21:58 UTC, syarasyoujyu commented
@matsuda-km
あの後色々webrtcについて行ったところ、[https://github.com/whitphx/streamlit-stt-app](url)など、streamlitのWebrtc自体が動かなかったです。GoogleでもMicrosoftEdgeでも同じでした。

2024-11-20 23:43 UTC, matsuda-tkm commented
本当ですねサンプルコード動かないですね

エラーログ（↑であげたやつ）で検索してみたらこれ↓が出てきてmediapipeのバージョン下げればいけるかもです

https://stackoverflow.com/questions/78493742/feedback-manager-requires-a-model-with-a-single-signature-inference

なので

```
mediapipe==0.10.9
streamlit==1.40.1
torch
```

2024-11-20 23:53 UTC, syarasyoujyu commented
そのため、pipのバージョンを変えてインストールする予定ですが大丈夫そうでしょうか？
自分のpipが20.4.1なのですが、どうやらそのverのmediapipeは対応外だそうです

2024-11-20 23:54 UTC, matsuda-tkm commented
本当にpipの問題ですかね？どういうエラーが出ますか？

2024-11-20 23:56 UTC, syarasyoujyu commented
何もインストールしていない仮想環境にて実行したらエラーが出ました。

>(venv_mp) C:\Users\yoko1\workspace\no-lose-janken-ai>pip install -r requirements.txt
ERROR: Could not find a version that satisfies the requirement mediapipe==0.10.9 (from versions: 0.10.13, 0.10.14, 0.10.18)
ERROR: No matching distribution found for mediapipe==0.10.9

2024-11-21 00:01 UTC, matsuda-tkm commented
python3.12だとinstallできませんでしたが、python3.11に下げたら行けました!

2024-11-21 00:52 UTC, matsuda-tkm commented on requirements.txt
> +mediapipe
```suggestion
mediapipe==0.10.9
```

2024-11-21 00:58 UTC, matsuda-tkm commented on app.py
> +    cap = cv2.VideoCapture(0)
```suggestion
    cap = cv2.VideoCapture(-1, cv2.CAP_V4L)
```

2024-11-21 01:17 UTC, syarasyoujyu reviewed
こっちはcap = cv2.VideoCapture(0)にしたらうまくいきました！（おそらくPC環境の違いですので気にしないで良さそうです）

2024-11-21 01:31 UTC, matsuda-tkm commented
なんか無理っぽいですね
https://discuss.streamlit.io/t/not-able-to-open-my-webcam-using-opencv/61952

huggingface spaceでも無理だったのですが、gradioであれば使えそうです。gradioに書き直せそうですか...。
（まあローカルで動いているのでそれで凌げはしますが）

https://huggingface.co/spaces/gradio/webcam

2024-11-21 01:37 UTC, matsuda-tkm commented
あ、このgradioのvideo captureってリアルタイム取り込みできるんですかね

2024-11-21 01:39 UTC, matsuda-tkm commented
あっちこっちいって申し訳ないですがstreamlit webrtcってバージョン下げたら上手く動かないですかね？

2024-11-21 01:43 UTC, syarasyoujyu commented
すみません。１時間ほど対応できません。
webrtcのdowngrade下での実行は１２時頃からやってきます

2024-11-21 01:54 UTC, matsuda-tkm commented
streamlit==1.38.0で動きました（webrtcは最新バージョンでも動きます）

2024-11-21 03:28 UTC, syarasyoujyu commented
サンプルコードを見ましたところ、webrtcのデプロイにはtwilioが必要なようです
[参考](https://github.com/whitphx/streamlit-stt-app/blob/main/app_deepspeech.py#L73)

2024-11-21 03:29 UTC, syarasyoujyu commented
なので、デプロイ用もかねてtwilioを使ったwebrtcを試してきます

2024-11-21 03:42 UTC, syarasyoujyu commented
こちらもできました！
ちなみにですが、デプロイにはtwilioが必要なようです。
[参考](https://github.com/whitphx/streamlit-stt-app/blob/main/app_deepspeech.py#L73)

2024-11-21 14:24 UTC, matsuda-tkm commented
ローカルで動かせるようにrequirements.txtとREADME.mdの整備お願いしてもいいですか？

参考
- https://github.com/kyoto-kaira/eye-track-cursor/
- https://github.com/kyoto-kaira/moving-kaira-kun/

2024-11-21 16:13 UTC, matsuda-tkm approved these changes
結果の表示方法ちょっと変えたりREADME作成しました。
mainにマージします。

2024-11-21 16:13 UTC, merged